default_platform(:ios)

platform :ios do
  lane :beta do
    api_key = app_store_connect_api_key(
      key_id: "GGY24CMB45",
      issuer_id: "98373153-0f44-4671-8acd-d71e5f250f65",
      key_filepath: File.expand_path("../../AuthKey_GGY24CMB45.p8", __dir__)
    )

    increment_version_number(
      version_number: "1.0",
      xcodeproj: "FastlaneTestDeploy.xcodeproj"
    )

    increment_build_number(
      build_number: 1,
      xcodeproj: "FastlaneTestDeploy.xcodeproj"
    )

    build_app(
      workspace: "FastlaneTestDeploy.xcworkspace",
      scheme: "FastlaneTestDeploy",
      clean: true,
      export_method: "app-store",
      xcargs: "-allowProvisioningUpdates",
      export_xcargs: "-allowProvisioningUpdates"
    )

    upload_to_testflight(
      api_key: api_key,
      distribute_external: false,
      skip_waiting_for_build_processing: true
    )
  end
end
